# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

# Tracing - see the note in application.properties
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
management.tracing.sampling.probability=1.0

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.addresses=rabbitmq:5672
